name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: /Users/jakkapong/Devs/Tutorial/github-workflows-rsync-deployment/site/
          remote_path: /var/www/html/
          remote_host: 178.128.120.239
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}